#!/bin/sh

# --- Install Android SDKs and other build packages

# Other tools and resources of Android SDK
#  you should only install the packages you need!
# To get a full list of available options you can use:
#  android list sdk --no-ui --all --extended
# (!!!) Only install one package at a time, as "echo y" will only work for one license!
#       If you don't do it this way you might get "Unknown response" in the logs,
#         but the android SDK tool **won't** fail, it'll just **NOT** install the package.
RUN echo y | android update sdk --no-ui --all --filter platform-tools | grep 'package installed'

# SDKs
# Please keep these in descending order!
echo y | android update sdk --no-ui --all --filter android-25 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-24 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-23 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-22 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-21 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-20 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter android-19 | grep 'package installed'

# build tools
# Please keep these in descending order!
echo y | android update sdk --no-ui --all --filter build-tools-25.0.1 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-25.0.0 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.3 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.2 | grep 'package installed'
echo y | android update sdk --no-ui --all --filter build-tools-23.0.1 | grep 'package installed'

# Extras
echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
echo y | android update sdk --no-ui --all --filter extra-google-m2repository | grep 'package installed'
