tap 'caskroom/cask'
tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/test-bot'
tap 'homebrew/versions'
cask 'java'
cask 'android-studio'
cask 'google-chrome'
#cask 'remote-desktop-connection'
brew 'git'
brew 'node@6'
brew 'yarn'
brew 'mas'
brew 'android-sdk'
#mas 'Xcode', id: 497799835
mas 'Slack', id: 803453959
